run:
  deadline: 120s
  tests: false

linters:
  enable-all: true
  disable:
  - gocyclo
  - gofmt
  - maligned
  fast: false

linter-settings:
  gofmt:
    simplify: false

issues:
  exclude:
  # gas
  - "G104: Errors unhandled." # Let errcheck handle these
  # golint
  - "(func|method|struct field|type|var) .* should be " # golint errors about variable names (don't want to fix them because they're in a public interface)
  - "Comment on exported"
  - "exported .* should have comment or be unexported"
  exclude-use-default: false
  max-same-issues: 1000
  max-per-linter: 1000
