version: 2.1

workflows:
  workflow:
    jobs:
      - go-test:
          name: Go 1.17
          docker-image: cimg/go:1.17
          run-lint: true
      - go-test:
          name: Go 1.16
          docker-image: cimg/go:1.16
      - go-test:
          name: Go 1.15
          docker-image: cimg/go:1.15
      - go-test:
          name: Go 1.14
          docker-image: cimg/go:1.14

jobs:
  go-test:
    parameters:
      docker-image:
        type: string
      run-lint:
        type: boolean
        default: false
  
    docker:
      - image: <<parameters.docker-image>>
        environment:
          CIRCLE_TEST_REPORTS: /tmp/circle-reports

    steps:
      - checkout

      - run:
          name: install go-junit-report
          command: go get -u github.com/jstemmer/go-junit-report

      - run:
          name: build and test
          command: make test | tee output.txt
      - run:
          name: process test results
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS
            go-junit-report < output.txt > $CIRCLE_TEST_REPORTS/junit.xml
          when: always
      - store_test_results:
          path: /tmp/circle-reports
      
      - when:
          condition: <<parameters.run-lint>>
          steps:
            - run: make lint

      # Now run the contract tests
      - setup_remote_docker  # necessary in order for the 2 containers we're creating to see each other
      - run:
          name: build contract test service
          command: cd contract-tests && go build
      - run:
          name: deploy contract test service in Docker
          command: |
            cd contract-tests && docker build --tag testserviceimage .
      - run:
          name: run contract test service
          command: |
            docker network create contract-tests-network
            docker run -d -p 8000:8000 --network contract-tests-network \
              --name testservice testserviceimage
      - run:
          name: run contract test harness
          command: |
            docker run -p 8111:8111 --network contract-tests-network --name testharness \
              ldcircleci/sse-contract-tests:1 --url http://testservice:8000 --host testharness          
      - run:
          name: show contract test service output
          when: always
          command: docker logs testservice
