version: 2.1

workflows:
  workflow:
    jobs:
      - go-test:
          name: Go 1.17
          docker-image: cimg/go:1.17
          run-lint: true
      - go-test:
          name: Go 1.16
          docker-image: cimg/go:1.16
      - go-test:
          name: Go 1.15
          docker-image: cimg/go:1.15
      - go-test:
          name: Go 1.14
          docker-image: cimg/go:1.14

jobs:
  go-test:
    parameters:
      docker-image:
        type: string
      run-lint:
        type: boolean
        default: false
  
    docker:
      - image: <<parameters.docker-image>>
        environment:
          CIRCLE_TEST_REPORTS: /tmp/circle-reports

    steps:
      - checkout

      - run:
          name: install go-junit-report
          command: go get -u github.com/jstemmer/go-junit-report

      - run:
          name: build and test
          command: make test | tee output.txt
      - run:
          name: process test results
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS
            go-junit-report < output.txt > $CIRCLE_TEST_REPORTS/junit.xml
          when: always
      - store_test_results:
          path: /tmp/circle-reports
      
      - when:
          condition: <<parameters.run-lint>>
          steps:
            - run: make lint

      - run:
          name: build contract test service
          command: cd contract-tests && go mod tidy && go build

      - run:
          name: start contract test service
          command: ./contract-tests/contract-tests
          background: true

      - run:
          name: run contract tests
          command: |
            curl -s https://raw.githubusercontent.com/launchdarkly/sse-contract-tests/v0.0.3/downloader/run.sh \
              | VERSION=v0 PARAMS="-url http://localhost:8000 -stop-service-at-end" sh
